darknet_ros:
  ros__parameters:
    subscribers:
      camera_reading:
        topic: /sensor/left_sc/image_raw
        queue_size: 1
    actions:
      camera_reading:
        topic: /sensor/left_sc/image_raw
    publishers:
      object_detector:
        topic: /darknet/left_sc/found_object
        queue_size: 1
        latch: false
      bounding_boxes:
        topic: /darknet/left_sc/detection
        queue_size: 1
        latch: false
      detection_image:
        topic: /darknet/left_sc/detection_image
        queue_size: 1
        latch: true
    image_view:
      enable_opencv: false
      wait_key_delay: 3
      enable_console_output: false
