darknet_ros:
  ros__parameters:
    yolo_model:
      config_file:
        name: yolo-sim_posts.cfg
      weight_file:
        name: yolo-sim_posts.weights
      threshold:
        value: 0.6
      detection_classes:
        names:
          - end
          - post
